import { createHash } from "node:crypto";
import type { MediaGenRuntimeVendorInput } from "./types.js";

export const COGVIDEOX3_T2V_MODEL_ID = "cogvideox-3";
export const COGVIDEOX3_T2V_ADAPTER_REVISION = "openclaw-cogvideox3-text2video-runtime/v1";
export const COGVIDEOX3_T2V_ROUTE_ID = "cogvideox.zhipu.v4.cogvideox_3.text2video.1080p.quality";
export const COGVIDEOX3_T2V_ENDPOINT_ID = "zhipu.v4.videos.generations";
export const COGVIDEOX3_T2V_PROFILE_ID =
  "cogvideox.openclaw-runtime.cogvideox_3.text2video.1080p.quality.v1";
// Generated by the server-owned CapabilityProfileRevision. Profile drift is
// rejected before any paid provider request leaves the user runtime.
export const COGVIDEOX3_T2V_PROFILE_DIGEST =
  "sha256:402c05765fa76114402b95d8157cd97a907635db4b3b16c0fffecd22290665b7";

const DURATIONS = new Set([5, 10]);
const FPS = new Set([30, 60]);
const SIZES = {
  "16:9": "1920x1080",
  "9:16": "1080x1920",
} as const;

export type CogVideoX3T2vCreateBody = {
  model: typeof COGVIDEOX3_T2V_MODEL_ID;
  prompt: string;
  quality: "quality";
  with_audio: boolean;
  watermark_enabled: true;
  size: (typeof SIZES)[keyof typeof SIZES];
  fps: 30 | 60;
  duration: 5 | 10;
};

export type CogVideoX3T2vCompileResult =
  | {
      ok: true;
      body: CogVideoX3T2vCreateBody;
      providerRequestDigest: string;
    }
  | { ok: false; message: string };

function fail(message: string): CogVideoX3T2vCompileResult {
  return { ok: false, message };
}

function validateFrozenIdentity(input: MediaGenRuntimeVendorInput): string | null {
  const plan = input.frozenPlan;
  if (
    !plan ||
    input.presetId !== "cogvideox" ||
    input.mode !== "text2video" ||
    plan.presetId !== input.presetId ||
    plan.mode !== input.mode ||
    plan.generationIntent.legacyMode !== input.mode ||
    plan.generationScenario !== "text_to_video" ||
    !["silent", "native_generate"].includes(plan.outputAudioPolicy) ||
    plan.adapterRevision !== COGVIDEOX3_T2V_ADAPTER_REVISION ||
    plan.providerRouteRef.routeId !== COGVIDEOX3_T2V_ROUTE_ID ||
    plan.providerRouteRef.providerId !== "zhipu_open_platform" ||
    plan.providerRouteRef.modelId !== COGVIDEOX3_T2V_MODEL_ID ||
    plan.providerRouteRef.endpointId !== COGVIDEOX3_T2V_ENDPOINT_ID ||
    plan.providerRouteRef.region !== "cn" ||
    plan.providerRouteRef.accountTier !== "api_key" ||
    plan.capabilityProfileRef.profileId !== COGVIDEOX3_T2V_PROFILE_ID ||
    plan.capabilityProfileRef.revision !== 1 ||
    plan.capabilityProfileRef.digest !== COGVIDEOX3_T2V_PROFILE_DIGEST
  ) {
    return "The frozen CogVideoX route/profile does not match CogVideoX-3 Text-to-Video.";
  }
  return input.prompt === plan.generationIntent.compiledPrompt
    ? null
    : "The runtime prompt does not match the frozen CogVideoX compiled prompt.";
}

function validateMappings(input: MediaGenRuntimeVendorInput): string | null {
  const plan = input.frozenPlan!;
  const fields = new Set([
    "scenario",
    "output.audio",
    "prompt",
    "output.durationSec",
    "output.aspectRatio",
    "output.resolution",
    "output.fps",
  ]);
  if (
    plan.constraintPlan.some(
      (row) =>
        row.providerSlot !== undefined ||
        (row.providerField !== undefined && !fields.has(row.providerField)),
    )
  ) {
    return "The frozen CogVideoX plan contains an unimplemented provider mapping.";
  }
  for (const [path, providerField] of [
    ["generationScenario", "scenario"],
    ["outputAudioPolicy", "output.audio"],
    ["output.durationSec", "output.durationSec"],
    ["output.aspectRatio", "output.aspectRatio"],
    ["output.resolution", "output.resolution"],
    ["output.fps", "output.fps"],
  ] as const) {
    const mapping = plan.constraintPlan.find((row) => row.intentPath === path);
    if (mapping?.support !== "native" || mapping.providerField !== providerField) {
      return `CogVideoX ${path} was not frozen as an exact native mapping.`;
    }
  }
  const prompt = plan.constraintPlan.find((row) => row.intentPath === "compiledPrompt");
  if (prompt?.support !== "prompt" || prompt.providerField !== "prompt") {
    return "The CogVideoX prompt was not frozen as the compiled provider prompt.";
  }
  if (Object.keys(input.params ?? {}).length > 0) {
    return "Unplanned provider parameters are not accepted by the CogVideoX-3 adapter.";
  }
  return null;
}

/** Compile one exact CogVideoX-3 text-to-video request without passthrough. */
export function compileCogVideoX3T2vRequest(
  input: MediaGenRuntimeVendorInput,
): CogVideoX3T2vCompileResult {
  const identityError = validateFrozenIdentity(input);
  if (identityError) {
    return fail(identityError);
  }
  const mappingError = validateMappings(input);
  if (mappingError) {
    return fail(mappingError);
  }

  const intent = input.frozenPlan!.generationIntent;
  const duration = intent.output.durationSec;
  const ratio = intent.output.aspectRatio;
  const fps = intent.output.fps;
  const promptLength = Array.from(intent.compiledPrompt).length;
  if (
    intent.generationScenario !== "text_to_video" ||
    !["silent", "native_generate"].includes(intent.outputAudioPolicy) ||
    intent.output.shotCount !== 1 ||
    typeof duration !== "number" ||
    !DURATIONS.has(duration) ||
    input.durationSec !== duration ||
    typeof ratio !== "string" ||
    !(ratio in SIZES) ||
    intent.output.resolution !== "1080p" ||
    input.resolution !== "1080p" ||
    typeof fps !== "number" ||
    !FPS.has(fps) ||
    intent.output.qualityIntent !== undefined ||
    promptLength < 1 ||
    promptLength > 512 ||
    intent.compiledPrompt.trim().length === 0 ||
    intent.narrative.negativePrompt !== undefined ||
    intent.references.length !== 0 ||
    input.source !== undefined ||
    (input.sources?.length ?? 0) !== 0
  ) {
    return fail("The frozen CogVideoX output constraints are incomplete or unsupported.");
  }

  const body: CogVideoX3T2vCreateBody = {
    model: COGVIDEOX3_T2V_MODEL_ID,
    prompt: intent.compiledPrompt,
    quality: "quality",
    with_audio: intent.outputAudioPolicy === "native_generate",
    // The exact route keeps the documented default compliance watermark on;
    // this is not a client-overridable provider-private parameter.
    watermark_enabled: true,
    size: SIZES[ratio as keyof typeof SIZES],
    fps: fps as 30 | 60,
    duration: duration as 5 | 10,
  };
  return {
    ok: true,
    body,
    providerRequestDigest: `sha256:${createHash("sha256")
      .update(JSON.stringify(body))
      .digest("hex")}`,
  };
}
