import { createHash } from "node:crypto";
import type { MediaGenerationIntentReference } from "./frozen-plan.js";
import type {
  MediaGenRuntimeSource,
  MediaGenRuntimeSourceSlot,
  MediaGenRuntimeVendorInput,
} from "./types.js";

export const COGVIDEOX3_FIRST_LAST_MODEL_ID = "cogvideox-3";
export const COGVIDEOX3_FIRST_LAST_ADAPTER_REVISION =
  "openclaw-cogvideox3-first-last-frame-runtime/v1";
export const COGVIDEOX3_FIRST_LAST_ROUTE_ID =
  "cogvideox.zhipu.v4.cogvideox_3.first_last_frame_to_video.1080p.quality";
export const COGVIDEOX3_FIRST_LAST_ENDPOINT_ID = "zhipu.v4.videos.generations";
export const COGVIDEOX3_FIRST_LAST_PROFILE_ID =
  "cogvideox.openclaw-runtime.cogvideox_3.first_last_frame_to_video.1080p.quality.v1";
// Generated by the server-owned CapabilityProfileRevision. Profile drift is
// rejected before any paid provider request leaves the user runtime.
export const COGVIDEOX3_FIRST_LAST_PROFILE_DIGEST =
  "sha256:e5614c5df3e123cc9c75ec41742e52d6607c76b0da3b6b7e8ae196263e47c237";

const MAX_IMAGE_BYTES = 5 * 1024 * 1024;
const IMAGE_MIME_TYPES = new Set(["image/jpeg", "image/png"]);
const DURATIONS = new Set([5, 10]);
const FPS = new Set([30, 60]);
const SIZES = {
  "16:9": "1920x1080",
  "9:16": "1080x1920",
} as const;

export type CogVideoX3FirstLastCreateBody = {
  model: typeof COGVIDEOX3_FIRST_LAST_MODEL_ID;
  image_url: [string, string];
  prompt: string;
  quality: "quality";
  with_audio: boolean;
  watermark_enabled: true;
  size: (typeof SIZES)[keyof typeof SIZES];
  fps: 30 | 60;
  duration: 5 | 10;
};

export type CogVideoX3FirstLastCompileResult =
  | {
      ok: true;
      body: CogVideoX3FirstLastCreateBody;
      providerRequestDigest: string;
    }
  | { ok: false; message: string };

function fail(message: string): CogVideoX3FirstLastCompileResult {
  return { ok: false, message };
}

function normalizedSha256(value: string | undefined): string | null {
  if (!value) {
    return null;
  }
  const hex = value.startsWith("sha256:") ? value.slice(7) : value;
  return /^[a-f0-9]{64}$/u.test(hex) ? hex : null;
}

function correlateSources(
  input: MediaGenRuntimeVendorInput,
): { ok: true; slots: Map<string, MediaGenRuntimeSourceSlot> } | { ok: false; message: string } {
  const references = input.frozenPlan?.generationIntent.references ?? [];
  if (input.source) {
    return { ok: false, message: "CogVideoX-3 first/last-frame requires typed reference slots." };
  }
  const sources = input.sources ?? [];
  if (sources.length !== references.length) {
    return {
      ok: false,
      message: "Resolved CogVideoX-3 frame count does not match the frozen plan.",
    };
  }
  const slots = new Map<string, MediaGenRuntimeSourceSlot>();
  for (const source of sources) {
    const key = `${source.role}:${source.ordinal}`;
    if (slots.has(key)) {
      return { ok: false, message: "Resolved CogVideoX-3 frame slots are not unique." };
    }
    slots.set(key, source);
  }
  for (const reference of references) {
    if (!slots.has(`${reference.role}:${reference.ordinal}`)) {
      return { ok: false, message: "A frozen CogVideoX-3 frame slot was not resolved." };
    }
  }
  return { ok: true, slots };
}

function frameDataUri(
  reference: MediaGenerationIntentReference,
  source: MediaGenRuntimeSource,
): string | null {
  if (
    reference.mediaClass !== "image" ||
    !reference.authorityVerified ||
    !source.bytes ||
    source.bytes.length === 0 ||
    source.bytes.length > MAX_IMAGE_BYTES ||
    source.providerRef
  ) {
    return null;
  }
  const mimeType = source.mimeType.trim().toLowerCase();
  if (
    !IMAGE_MIME_TYPES.has(mimeType) ||
    (reference.mimeType !== undefined && reference.mimeType.trim().toLowerCase() !== mimeType)
  ) {
    return null;
  }
  const expectedSha256 = normalizedSha256(reference.sourceDigest);
  const resolvedSha256 = normalizedSha256(source.sha256);
  const actualSha256 = createHash("sha256").update(source.bytes).digest("hex");
  if (!expectedSha256 || resolvedSha256 !== expectedSha256 || actualSha256 !== expectedSha256) {
    return null;
  }
  return `data:${mimeType};base64,${source.bytes.toString("base64")}`;
}

function validateFrozenIdentity(input: MediaGenRuntimeVendorInput): string | null {
  const plan = input.frozenPlan;
  if (
    !plan ||
    input.presetId !== "cogvideox" ||
    input.mode !== "image2video" ||
    plan.presetId !== input.presetId ||
    plan.mode !== input.mode ||
    plan.generationIntent.legacyMode !== input.mode ||
    plan.generationScenario !== "first_last_frame_to_video" ||
    !["silent", "native_generate"].includes(plan.outputAudioPolicy) ||
    plan.adapterRevision !== COGVIDEOX3_FIRST_LAST_ADAPTER_REVISION ||
    plan.providerRouteRef.routeId !== COGVIDEOX3_FIRST_LAST_ROUTE_ID ||
    plan.providerRouteRef.providerId !== "zhipu_open_platform" ||
    plan.providerRouteRef.modelId !== COGVIDEOX3_FIRST_LAST_MODEL_ID ||
    plan.providerRouteRef.endpointId !== COGVIDEOX3_FIRST_LAST_ENDPOINT_ID ||
    plan.providerRouteRef.region !== "cn" ||
    plan.providerRouteRef.accountTier !== "api_key" ||
    plan.capabilityProfileRef.profileId !== COGVIDEOX3_FIRST_LAST_PROFILE_ID ||
    plan.capabilityProfileRef.revision !== 1 ||
    plan.capabilityProfileRef.digest !== COGVIDEOX3_FIRST_LAST_PROFILE_DIGEST
  ) {
    return "The frozen CogVideoX route/profile does not match first/last-frame generation.";
  }
  return input.prompt === plan.generationIntent.compiledPrompt
    ? null
    : "The runtime prompt does not match the frozen CogVideoX compiled prompt.";
}

function validateMappings(input: MediaGenRuntimeVendorInput): string | null {
  const plan = input.frozenPlan!;
  const fields = new Set([
    "scenario",
    "output.audio",
    "prompt",
    "output.durationSec",
    "output.aspectRatio",
    "output.resolution",
    "output.fps",
  ]);
  const slots = new Set(["references.first_frame", "references.last_frame"]);
  if (
    plan.constraintPlan.some(
      (row) =>
        (row.providerSlot !== undefined && !slots.has(row.providerSlot)) ||
        (row.providerField !== undefined && !fields.has(row.providerField)),
    )
  ) {
    return "The frozen CogVideoX plan contains an unimplemented provider mapping.";
  }
  for (const [path, providerField] of [
    ["generationScenario", "scenario"],
    ["outputAudioPolicy", "output.audio"],
    ["output.durationSec", "output.durationSec"],
    ["output.aspectRatio", "output.aspectRatio"],
    ["output.resolution", "output.resolution"],
    ["output.fps", "output.fps"],
  ] as const) {
    const mapping = plan.constraintPlan.find((row) => row.intentPath === path);
    if (mapping?.support !== "native" || mapping.providerField !== providerField) {
      return `CogVideoX ${path} was not frozen as an exact native mapping.`;
    }
  }
  const prompt = plan.constraintPlan.find((row) => row.intentPath === "compiledPrompt");
  if (prompt?.support !== "prompt" || prompt.providerField !== "prompt") {
    return "The CogVideoX prompt was not frozen as the compiled provider prompt.";
  }
  for (const role of ["first_frame", "last_frame"] as const) {
    const frame = plan.constraintPlan.find((row) => row.intentPath === `references.${role}.0`);
    if (frame?.support !== "native" || frame.providerSlot !== `references.${role}`) {
      return `The CogVideoX ${role} was not frozen as an exact native slot.`;
    }
  }
  if (Object.keys(input.params ?? {}).length > 0) {
    return "Unplanned provider parameters are not accepted by the CogVideoX-3 adapter.";
  }
  return null;
}

/** Compile exactly two verified frames in provider-documented first-then-last order. */
export function compileCogVideoX3FirstLastRequest(
  input: MediaGenRuntimeVendorInput,
): CogVideoX3FirstLastCompileResult {
  const identityError = validateFrozenIdentity(input);
  if (identityError) {
    return fail(identityError);
  }
  const mappingError = validateMappings(input);
  if (mappingError) {
    return fail(mappingError);
  }

  const intent = input.frozenPlan!.generationIntent;
  const duration = intent.output.durationSec;
  const ratio = intent.output.aspectRatio;
  const fps = intent.output.fps;
  const promptLength = Array.from(intent.compiledPrompt).length;
  if (
    intent.generationScenario !== "first_last_frame_to_video" ||
    !["silent", "native_generate"].includes(intent.outputAudioPolicy) ||
    intent.output.shotCount !== 1 ||
    typeof duration !== "number" ||
    !DURATIONS.has(duration) ||
    input.durationSec !== duration ||
    typeof ratio !== "string" ||
    !(ratio in SIZES) ||
    intent.output.resolution !== "1080p" ||
    input.resolution !== "1080p" ||
    typeof fps !== "number" ||
    !FPS.has(fps) ||
    intent.output.qualityIntent !== undefined ||
    promptLength < 1 ||
    promptLength > 512 ||
    intent.compiledPrompt.trim().length === 0 ||
    intent.narrative.negativePrompt !== undefined ||
    input.source !== undefined
  ) {
    return fail("The frozen CogVideoX output constraints are incomplete or unsupported.");
  }

  const references = intent.references;
  const firstFrames = references.filter((item) => item.role === "first_frame");
  const lastFrames = references.filter((item) => item.role === "last_frame");
  if (
    references.length !== 2 ||
    firstFrames.length !== 1 ||
    lastFrames.length !== 1 ||
    firstFrames[0]?.ordinal !== 0 ||
    lastFrames[0]?.ordinal !== 0
  ) {
    return fail("CogVideoX-3 first/last-frame requires exactly one typed frame per role.");
  }
  const correlated = correlateSources(input);
  if (!correlated.ok) {
    return fail(correlated.message);
  }
  const firstFrame = firstFrames[0];
  const lastFrame = lastFrames[0];
  const firstImage = frameDataUri(
    firstFrame,
    correlated.slots.get(`${firstFrame.role}:${firstFrame.ordinal}`)!.source,
  );
  const lastImage = frameDataUri(
    lastFrame,
    correlated.slots.get(`${lastFrame.role}:${lastFrame.ordinal}`)!.source,
  );
  if (!firstImage || !lastImage) {
    return fail("A frozen CogVideoX frame failed size, MIME, or digest verification.");
  }

  const body: CogVideoX3FirstLastCreateBody = {
    model: COGVIDEOX3_FIRST_LAST_MODEL_ID,
    image_url: [firstImage, lastImage],
    prompt: intent.compiledPrompt,
    quality: "quality",
    with_audio: intent.outputAudioPolicy === "native_generate",
    watermark_enabled: true,
    size: SIZES[ratio as keyof typeof SIZES],
    fps: fps as 30 | 60,
    duration: duration as 5 | 10,
  };
  return {
    ok: true,
    body,
    providerRequestDigest: `sha256:${createHash("sha256")
      .update(JSON.stringify(body))
      .digest("hex")}`,
  };
}
